AWSTemplateFormatVersion: 2010-09-09
Description: Part 2 - creacion de una EC2 y el SG mediante un stack con CloudFormation

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0d5eff06f840b45e9 # ID valido Solo en la region: us-east-1
      InstanceType: t2.micro
      Tags: 
        - Key: Name 
          Value: Nuestra Primera EC2
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
        
        
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Join ["-", [EC2-security-group, dev]]
      GroupDescription: "Permitir acceso HTTP/HTTPS y SSH para el trafico entrante y saliente"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
